spring:
  # ─────────────────────────────────────
  # 1. MySQL
  # ─────────────────────────────────────
  datasource:
    url: jdbc:mysql://localhost:3307/jpabegin?characterEncoding=utf8
    username: jpauser
    password: jpapass
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ─────────────────────────────────────
  # 2. Oacle
  # ─────────────────────────────────────
  oracle:
    url: jdbc:oracle:thin:@localhost:1521:XEPDB1
    username: localuser
    password: localuser
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none   # 개발환경: update / 운영 시 validate 권장
    properties:
      hibernate:
        format_sql: true
    show-sql: true